### ISSUE TITLE
Use spl_autoload_register to a proper auto loading

### ISSUE THREAD

**Issue by darknessxk** [FinGu/file_uploader#1]
Your autoloading method seems enough for this project but i am pretty sure that can be better using the proper auto loading with lazy loading with spl-autoload-register instead of loading everything in one chunk there is a link to help u

https://www.php.net/manual/en/function.spl-autoload-register.php

**Comment by FinGu** [comment]
i can't use that function for two reasons, the only class i have in this project is the response_structure one and the file names aren't the same as the class/namespace name

**Comment by FinGu** [comment]
oh yeah, and because of this too XD
![image](https://user-images.githubusercontent.com/50637180/96951393-cb2f0780-14c2-11eb-8624-0c02e54d8357.png)

**Comment by darknessxk** [comment]
Fair enough :p but u maybe could abuse oop powers with php and hack for sure
